version: '3.8'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ddb_data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    environment:
      - "MINIO_ROOT_USER=minio"
      - "MINIO_ROOT_PASSWORD=minio123"
    command: server /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint:
      - /bin/sh
      - -ex
      - -c
    command:
      - |
        /usr/bin/mc alias set myminio http://minio:9000 minio minio123
        /usr/bin/mc mb myminio/iac-store
        /usr/bin/mc anonymous set public myminio/iac-store

volumes:
  minio_data:
  ddb_data:
