export const awsRegions: { [key: string]: string } = {
  "us-east-2": "us-east-2 (Ohio)",
  "us-east-1": "us-east-1 (N. Virginia)",
  "us-west-1": "us-west-1 (N. California)",
  "us-west-2": "us-west-2 (Oregon)",
  "af-south-1": "af-south-1 (Cape Town)",
  "ap-east-1": "ap-east-1 (Hong Kong)",
  "ap-south-2": "ap-south-2 (Hyderabad)",
  "ap-southeast-3": "ap-southeast-3 (Jakarta)",
  "ap-southeast-4": "ap-southeast-4 (Melbourne)",
  "ap-south-1": "ap-south-1 (Mumbai)",
  "ap-northeast-3": "ap-northeast-3 (Osaka)",
  "ap-northeast-2": "ap-northeast-2 (Seoul)",
  "ap-southeast-1": "ap-southeast-1 (Singapore)",
  "ap-southeast-2": "ap-southeast-2 (Sydney)",
  "ap-northeast-1": "ap-northeast-1 (Tokyo)",
  "ca-central-1": "ca-central-1 (Central)",
  "ca-west-1": "ca-west-1 (Calgary)",
  "eu-central-1": "eu-central-1 (Frankfurt)",
  "eu-west-1": "eu-west-1 (Ireland)",
  "eu-west-2": "eu-west-2 (London)",
  "eu-south-1": "eu-south-1 (Milan)",
  "eu-west-3": "eu-west-3 (Paris)",
  "eu-south-2": "eu-south-2 (Spain)",
  "eu-north-1": "eu-north-1 (Stockholm)",
  "eu-central-2": "eu-central-2 (Zurich)",
  "il-central-1": "il-central-1 (Tel Aviv)",
  "me-south-1": "me-south-1 (Bahrain)",
  "me-central-1": "me-central-1 (UAE)",
  "sa-east-1": "sa-east-1 (São Paulo)",
};

export const awsSupportedRegions = {
  "us-east-1": "us-east-1 (N. Virginia)",
  "us-west-2": "us-west-2 (Oregon)",
  "ap-south-1": "ap-south-1 (Mumbai)",
  "eu-west-1": "eu-west-1 (Ireland)",
  "eu-west-2": "eu-west-2 (London)",
};
