FROM public.ecr.aws/lambda/python:3.12

COPY ./requirements.txt ${LAMBDA_TASK_ROOT}

RUN pip3 install \
        --target ${LAMBDA_TASK_ROOT} \
        -r ${LAMBDA_TASK_ROOT}/requirements.txt

COPY . ${LAMBDA_TASK_ROOT}

ENV PYTHONPATH=${LAMBDA_TASK_ROOT}:${PYTHONPATH}

CMD [ "main.lambda_handler" ]
