name: Deploy

env:
  NODE_VERSION: "20.x"
  PYTHON_VERSION: "3.11"

on:
  workflow_call:
    inputs:
      stage:
        description: The stage (environment) of the deployment
        required: true
        type: string
      region:
        description: The region to deploy to
        required: true
        type: string
        default: us-east-1
      engine-ref:
        description: the ref (branch, tag or SHA) of the engine to build
        required: false
        type: string
        default: main
  workflow_dispatch:
    inputs:
      stage:
        description: The stage (environment) of the deployment
        required: true
        type: environment
      region:
        description: The region to deploy to
        required: true
        type: string
        default: us-east-1
      engine-ref:
        required: false
        type: string
        default: main

concurrency:
  group: ci-${{ inputs.stage }}-${{ inputs.region }}

jobs:

  build-binaries:
    name: Build Binaries (engine, iac)
    uses: ./.github/workflows/build_binaries.yaml
    with:
      klotho-ref: ${{ inputs.engine-ref }}
    secrets: inherit

  deploy:
    needs:
      - build-binaries
    runs-on: ubuntu-latest
    environment: ${{ inputs.stage }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install pipenv
        run: pip install pipenv
      - name: export requirements.txt
        run: pipenv requirements > requirements.txt     
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ inputs.region }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Pulumi Refresh
        uses: pulumi/actions@v4
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ""
          AWS_REGION: ${{ inputs.region }}
          STAGE: ${{ inputs.stage }}
          AUTH0_DOMAIN: ${{ vars.AUTH0_DOMAIN }}
          AUTH0_AUDIENCE: ${{ vars.AUTH0_AUDIENCE }}
        with:
          command: refresh
          work-dir: "./deploy"
          stack-name: "stacksnap-${{ inputs.stage }}-${{ inputs.region }}"
          upsert: true
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install
        run: npm install
        working-directory: ./deploy
      - name: pulumi - up
        uses: pulumi/actions@v4
        with:
          command: up
          work-dir: "./deploy"
          stack-name: "stacksnap-${{ inputs.stage }}-${{ inputs.region }}"
          upsert: true
          config-map: |
            {
              aws:region: { value: "${{ inputs.region }}", secret: false },
            }
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ""
          AWS_REGION: ${{ inputs.region }}
          STAGE: ${{ inputs.stage }}
          AUTH0_DOMAIN: ${{ vars.AUTH0_DOMAIN }}
          AUTH0_AUDIENCE: ${{ vars.AUTH0_AUDIENCE }}
      - name: Get Pulumi Outputs
        id: pulumi-outputs
        run: |
          echo "stacksnap_binaries_BucketName=$(pulumi stack output stacksnap_binaries_BucketName)" >> $GITHUB_OUTPUT
          echo "stacksnap_ui_BucketName=$(pulumi stack output stacksnap_ui_BucketName)" >> $GITHUB_OUTPUT
        working-directory: ./deploy
        shell: bash
      - name: build frontend
        run: |
          make frontend/node_modules
          make build-frontend-${STAGE}
        env:
          CI: false
          NODE_OPTIONS: "--max-old-space-size=4096"
          STAGE: ${{ inputs.stage }}
      - name: Upload frontend to S3
        run: |
          aws s3 sync frontend/dist/ s3://${{ steps.pulumi-outputs.outputs.stacksnap_ui_BucketName }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.region }}
      - name: Download Binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: binaries
      - name: Upload binaries to S3
        run: |
          aws s3 sync binaries/ s3://${{ steps.pulumi-outputs.outputs.stacksnap_binaries_BucketName }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.region }}
      - name: Invalidate CloudFront Cache
        run: |
          distributionArn=$(aws resourcegroupstaggingapi get-resources --tag-filters Key=RESOURCE_NAME,Values=stacksnap-distribution --region ${{ inputs.region }} --resource-type-filters cloudfront:distribution --query "ResourceTagMappingList[0].ResourceARN" --output text)
          aws cloudfront create-invalidation --distribution-id "${distributionArn##*/}" --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.region }}
      - name: Upload Secrets
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.region }}
        run: |
          aws secretsmanager put-secret-value --secret-id stacksnap-pulumi-access-token --secret-string "${PULUMI_ACCESS_TOKEN}"
      - name: pulumi - up
        uses: pulumi/actions@v4
        with:
          command: up
          work-dir: "./deploy"
          stack-name: "stacksnap-${{ inputs.stage }}-${{ inputs.region }}"
          upsert: true
          config-map: |
            {
              aws:region: { value: "${{ inputs.region }}", secret: false },
            }
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ""
          AWS_REGION: ${{ inputs.region }}
          STAGE: ${{ inputs.stage }}
          AUTH0_DOMAIN: ${{ vars.AUTH0_DOMAIN }}
          AUTH0_AUDIENCE: ${{ vars.AUTH0_AUDIENCE }}
